name: Récupération et traitement journaliers des données DECP

on:
  schedule:
      - cron: '0 0 * * *'
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ryusryus/decp-monitoring-v2
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Récupération des données
      run: wget -O data/decp.json https://www.data.gouv.fr/fr/datasets/r/16962018-5c31-4296-9454-5998585496d2
    - 
      name: Création de decp_extracted.json
      run: python json_to_metajson.py
      
    -
      name: Test
      run: ls
    - name: Test2
      run: cd data/ && ls 
    -
      name: Push
      run: git config --global user.email "loldebite@gmail.com" && git add * && git commit -m "Mise à jour automatique des données" && git push
