name: Docker Image CI

on:
  schedule:
      - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      cache-key-suffix:
        description: Suffixe clé de cache (0 par défaut)
        type: string
        required: true
        default: '0'
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.KEY }}
    container:
      image: 139bercy/decp-monitoring-v2
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Récupération des données
      run: wget -O data/decp.json https://www.data.gouv.fr/fr/datasets/r/16962018-5c31-4296-9454-5998585496d2
    - 
      name: Création de decp_extracted.json
      run: python json_to_metajson.py
  
  
